import puppeteer from 'puppeteer-core'; import fs from 'fs';
const [url, prefix, w = 1440, h = 900] = process.argv.slice(2);
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', protocolTimeout: 600000, args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage(); p.on('pageerror', e => console.log('ERR', e.message)); p.on('console', m => { if (/error/i.test(m.type())) console.log('console', m.text()); });
await p.setViewport({ width: +w, height: +h });
await p.goto(url, { waitUntil: 'load', timeout: 120000 }); await p.waitForFunction('window.__ready', { timeout: 300000 });
const clickText = (sel, text) => p.evaluate((sel, text) => { const el = [...document.querySelectorAll(sel)].find(e => e.textContent.trim() === text); el?.click(); return !!el; }, sel, text);
await clickText('.btns button', 'Duplicate');
await p.evaluate(() => { const b = [...document.querySelectorAll('.swatch')].find(x => x.title === 'Liquid Silver'); b.click(); });
await clickText('.btns button', 'Duplicate');
await p.evaluate(() => { const b = [...document.querySelectorAll('.swatch')].find(x => x.title === 'Midnight Blue'); b.click(); });
await p.evaluate(() => { halide.cars[1].s.lat = -3.4; halide.cars[1].s.near = 16; halide.cars[1].s.rot = 330; halide.cars[2].s.lat = 3.6; halide.cars[2].s.near = 17; halide.cars[2].s.rot = 45; halide.cars[0].s.near = 11; halide.state.focal = 35; halide.setFocal(35); halide.markDirty(); });
await p.evaluate(() => [...document.querySelectorAll('.seg.cars button')][1].click());
console.log('cars', await p.evaluate(() => halide.cars.length), await p.evaluate(() => document.querySelector('.seg.cars').textContent));
await new Promise(r => setTimeout(r, 6000));
await p.screenshot({ path: `${prefix}-multi.png` });
const r = await p.evaluate(async () => { halide.state.aspect = '1:1'; const { blob, w, h } = await halide.exportPhoto(700); const buf = await blob.arrayBuffer(); let s = ''; const u = new Uint8Array(buf); for (let i = 0; i < u.length; i += 8192) s += String.fromCharCode(...u.subarray(i, i + 8192)); return { w, h, b64: btoa(s) }; });
fs.writeFileSync(`${prefix}-sq.jpg`, Buffer.from(r.b64, 'base64')); console.log('sq', r.w, r.h);
await b.close(); console.log('done');
