// CC0 HDRIs from Poly Haven (https://polyhaven.com).
// height: camera height of the original capture (m), projects the ground.
// sun: false when the brightest spot is not a real sun (dusk glow); soft: shadow blur multiplier for a near light (street lamp).
// u: horizontal panorama position (0..1) of a clear, flat spot for the car.
export const LOCATIONS = [
  { id: 'zwartkops_straight_afternoon', dust: '#8f8578', name: 'Zwartkops', place: 'Race circuit, Pretoria', height: 1.6, u: 0.31, track: true },
  { id: 'goegap_road', sunScale: 0.25, dust: '#a57a5c', name: 'Goegap', place: 'Desert road, Namaqualand', height: 1.7, u: 0.462, kind: 'nature' },
  { id: 'wide_street_01', name: 'Boulevard', place: 'Wide street, midday', height: 1.7, u: 0.39, kind: 'city' },
  { id: 'modern_evening_street', name: 'Glass District', place: 'City street, evening', height: 1.7, u: 0.595, sun: false, kind: 'city' },
  { id: 'cobblestone_street_night', name: 'Old Town', place: 'Cobblestones, night', height: 1.7, u: 0.46, soft: 3.5, kind: 'city' },
  { id: 'mealie_road', sunScale: 0.25, dust: '#a88f6e', name: 'Mealie Road', place: 'Farm road, golden hour', height: 1.7, u: 0.62, kind: 'nature' },
  { id: 'lonely_road_afternoon', sunScale: 0.25, dust: '#a88f6e', name: 'Lonely Road', place: 'Farm road, late sun', height: 1.7, u: 0.0, kind: 'nature' },
  { id: 'german_town_street', name: 'Stadtrand', place: 'Town edge, midday', height: 1.7, u: 0.12, kind: 'city' },
  { id: 'derelict_highway_noon', dust: '#9a9086', name: 'Old Highway', place: 'Cracked concrete, noon', height: 1.7, u: 0.58, kind: 'city' },
  { id: 'rural_asphalt_road', name: 'Country Lane', place: 'Asphalt bend, summer', height: 1.7, u: 0.0, kind: 'nature' },
  { id: 'simons_town_harbour', name: "Simon's Town", place: 'Harbour quay, morning', height: 1.7, u: 0.97, kind: 'city' },
  { id: 'horn-koppe_snow', name: 'Horn-Koppe', place: 'Snowfield, clear sky', height: 1.7, u: 0.2, kind: 'nature' },
  { id: 'shanghai_bund', name: 'The Bund', place: 'Riverside promenade, Shanghai, night', height: 1.7, u: 0.56, sun: false, iconic: true },
  { id: 'neuer_zollhof', name: 'Medienhafen', place: 'Gehry towers, Düsseldorf, dusk', height: 1.7, u: 0.2, iconic: true },
  { id: 'potsdamer_platz', name: 'Potsdamer Platz', place: 'City crossing, Berlin', height: 1.7, u: 0.6, iconic: true },
  { id: 'quattro_canti', name: 'Quattro Canti', place: 'Baroque crossroads, Palermo', height: 1.7, u: 0.4, iconic: true },
  { id: 'venice_sunset', sunScale: 0.25, name: 'Venice', place: 'Waterfront, sunset', height: 1.7, u: 0.85, iconic: true },
  { id: 'zwartkops_start_sunset', sunScale: 0.25, dust: '#8f8578', name: 'Zwartkops Grid', place: 'Start/finish straight, sunset', height: 1.7, u: 0.4, track: true },
  { id: 'zwartkops_curve_sunset', sunScale: 0.25, dust: '#8f8578', name: 'Zwartkops Hairpin', place: 'Track curve, sunset', height: 1.7, u: 0.88, track: true },
  { id: 'zwartkops_pit', name: 'Zwartkops Pit Lane', place: 'Covered pits, trackside', height: 1.7, u: 0.42, track: true, white: 3 },
  { id: 'skidpan', name: 'Skidpan', place: 'Test pad, stormy sky', height: 1.7, u: 0.3, track: true },
  { id: 'kart_club', name: 'Kart Club', place: 'Indoor kart track', height: 1.7, u: 0.52, track: true, sun: false },
  { id: 'piazza_san_marco', name: 'Piazza San Marco', place: 'Venice, morning', height: 1.7, u: 0.5, iconic: true },
  { id: 'st_peters_square_night', name: "St Peter's Square", place: 'Vatican City, night', height: 1.7, u: 0.27, sun: false, iconic: true },
  { id: 'colosseum', name: 'Colosseum', place: 'Rome, afternoon', height: 1.7, u: 0.85, iconic: true },
  { id: 'vatican_road', name: 'Vatican Road', place: 'Rome street, day', height: 1.7, u: 0.21, iconic: true },
  { id: 'signal_hill_sunrise', sunScale: 0.25, name: 'Signal Hill', place: 'Mountain road, Cape Town, sunrise', height: 1.7, u: 0.995, iconic: true, kind: 'nature' },
  { id: 'shanghai_riverside', name: 'Pudong', place: 'Riverside, Shanghai, day', height: 1.7, u: 0.1, iconic: true },
  { id: 'qwantani_dusk_1', sunScale: 0.25, dust: '#a88f6e', name: 'Qwantani', place: 'Savanna at dusk, Free State', height: 1.7, u: 0.125, kind: 'nature' },
  { id: 'autumn_park', name: 'Autumn Park', place: 'Tree-lined path, autumn', height: 1.7, u: 0.625, kind: 'nature' },
  { id: 'snowy_park_01', name: 'Snowy Park', place: 'Park walk, winter', height: 1.7, u: 0.5, kind: 'nature' },
  { id: 'satara_night', name: 'Satara', place: 'Bushveld night, Kruger', height: 1.7, u: 0.5, sun: false, kind: 'nature' },
  { id: 'urban_alley_01', name: 'Graffiti Alley', place: 'Back street, day', height: 1.7, u: 0.125, kind: 'city' },
  { id: 'industrial_sunset_02', sunScale: 0.25, name: 'Industrial Sunset', place: 'Factory estate, sundown', height: 1.7, u: 0.625, kind: 'city' },
  { id: 'hansaplatz', name: 'Hansaplatz', place: 'City square, Berlin, night', height: 1.7, u: 0.125, sun: false, kind: 'city' },
  { id: 'kloofendal_48d_partly_cloudy', dust: '#a88f6e', name: 'Kloofendal', place: 'Nature reserve, Johannesburg', height: 1.7, u: 0.125, kind: 'nature' },
  // backplates: flat photos of famous circuits (Wikimedia Commons, credited). light = the Poly Haven HDRI that lights the car,
  // u = which way the camera faces inside that HDRI (sets where the sun comes from), f35 = 35mm-equivalent lens,
  // hz = horizon row in the photo (0 top .. 1 bottom), camH = camera height (m)
  { id: 'monza_straight', plate: true, track: true, name: 'Monza', place: 'Main straight, Autodromo Nazionale', light: 'zwartkops_straight_afternoon', u: 0.31, f35: 160, hz: 0.4, camH: 1.6, height: 1.7, credit: 'Photo: United Autosports, CC BY-SA 2.0, via Wikimedia Commons' },
  { id: 'spa_a', plate: true, track: true, name: 'Spa-Francorchamps', place: 'La Source, Belgium', light: 'skidpan', u: 0.3, f35: 29, hz: 0.48, camH: 1.5, near: 11, lat: 0, height: 1.7, credit: 'Photo: FrDr, CC BY-SA 4.0, via Wikimedia Commons' },
  { id: 'monaco_pits', plate: true, track: true, name: 'Monaco', place: 'Pit lane, Circuit de Monaco', light: 'colosseum', u: 0.31, f35: 29, hz: 0.53, camH: 1.5, near: 10, lat: -1, height: 1.7, credit: 'Photo: Alexander Migl, CC BY-SA 4.0, via Wikimedia Commons' },
  { id: 'bathurst_a', plate: true, track: true, name: 'Mount Panorama', place: 'Bathurst, NSW', light: 'zwartkops_straight_afternoon', u: 0.31, f35: 24, hz: 0.62, camH: 1.5, near: 10, lat: 3, height: 1.7, credit: 'Photo: FotoSleuth, CC BY 2.0, via Wikimedia Commons' },
  { id: 'interlagos_senna', plate: true, track: true, name: 'Interlagos', place: 'S do Senna, São Paulo', light: 'skidpan', boost: 1.4, u: 0.3, f35: 29, hz: 0.48, camH: 1.5, height: 1.7, credit: 'Photo: Audi do Brasil, CC BY-SA 4.0, via Wikimedia Commons' },
  { id: 'suzuka_pits', plate: true, track: true, name: 'Suzuka', place: 'Pit straight, Japan', light: 'skidpan', u: 0.3, boost: 1.35, f35: 28, hz: 0.5, camH: 1.5, near: 11, lat: 0, height: 1.7, credit: 'Photo: Mamusi Taka, CC BY-SA 3.0, via Wikimedia Commons' },
  { id: 'suzuka_t1', plate: true, track: true, name: 'Suzuka Turn 1', place: 'First corner, Japan', light: 'skidpan', u: 0.3, boost: 1.35, f35: 28, hz: 0.3, camH: 1.5, near: 11, lat: 0, height: 1.7, credit: 'Photo: Mamusi Taka, CC BY-SA 3.0, via Wikimedia Commons' },
  { id: 'suzuka_12', plate: true, track: true, name: 'Suzuka Esses', place: 'Trackside, Japan', light: 'skidpan', u: 0.3, boost: 1.35, f35: 28, hz: 0.52, camH: 1.5, near: 11, lat: 0, height: 1.7, credit: 'Photo: Mamusi Taka, CC BY-SA 3.0, via Wikimedia Commons' },
];
export function bearingFromU(u) { const t = (u - 0.5) * 2 * Math.PI; return Math.atan2(-Math.cos(t), -Math.sin(t)); }
export const MAX_FOCAL = 135; // mm; past this an 8k panorama backdrop visibly softens
